/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cumulative.poetry;

import cumulative.poetry.common.AppConstants;
import cumulative.poetry.models.Poem;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class PoemTest {

    private Poem poem = null;

    @Before
    public void setUp() throws Exception {
        Poem poem = new Poem();
    }

    @Test public void shouldTestForRevealPoetryDayWise() {
        String actualValue = poem.revealPoetryDayWise(1);
        String expectedValue = AppConstants.THIS_IS_STRING + AppConstants.DAY1_POETRY + "\n";
        assertEquals(expectedValue,actualValue);

         actualValue = poem.revealPoetryDayWise(2);
         expectedValue = AppConstants.THIS_IS_STRING + AppConstants.DAY2_POETRY +"\n" +AppConstants.DAY1_POETRY + "\n";
        assertEquals(expectedValue,actualValue);
    }

}
