/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cumulative.poetry;

import cumulative.poetry.common.AppConstants;
import cumulative.poetry.common.PoetUtils;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class PoetTest {

    // This constant is used just in testing. That holds the actual value the recite method should return.
    public static String RECITE_ACTUAL_VALUE = "Day 1 - \n" +
            "This is the house that Jack built.\n" +
            "\n" +
            "Day 2 - \n" +
            "This is the malt that lay in\n" +
            "the house that Jack built.\n" +
            "\n" +
            "Day 3 - \n" +
            "This is the rat that ate\n" +
            "the malt that lay in\n" +
            "the house that Jack built.\n" +
            "\n" +
            "Day 4 - \n" +
            "This is the cat that killed\n" +
            "the rat that ate\n" +
            "the malt that lay in\n" +
            "the house that Jack built.\n" +
            "\n" +
            "Day 5 - \n" +
            "This is the dog that worried\n" +
            "the cat that killed\n" +
            "the rat that ate\n" +
            "the malt that lay in\n" +
            "the house that Jack built.\n" +
            "\n" +
            "Day 6 - \n" +
            "This is that cow with the crumpled horn that tossed\n" +
            "the dog that worried\n" +
            "the cat that killed\n" +
            "the rat that ate\n" +
            "the malt that lay in\n" +
            "the house that Jack built.\n" +
            "\n" +
            "Day 7 - \n" +
            "This is the maiden all forlorn that milked\n" +
            "that cow with the crumpled horn that tossed\n" +
            "the dog that worried\n" +
            "the cat that killed\n" +
            "the rat that ate\n" +
            "the malt that lay in\n" +
            "the house that Jack built.\n" +
            "\n" +
            "Day 8 - \n" +
            "This is the man all tattered and torn that kissed\n" +
            "the maiden all forlorn that milked\n" +
            "that cow with the crumpled horn that tossed\n" +
            "the dog that worried\n" +
            "the cat that killed\n" +
            "the rat that ate\n" +
            "the malt that lay in\n" +
            "the house that Jack built.\n" +
            "\n" +
            "Day 9 - \n" +
            "This is the priest all shaven and shorn that married\n" +
            "the man all tattered and torn that kissed\n" +
            "the maiden all forlorn that milked\n" +
            "that cow with the crumpled horn that tossed\n" +
            "the dog that worried\n" +
            "the cat that killed\n" +
            "the rat that ate\n" +
            "the malt that lay in\n" +
            "the house that Jack built.\n" +
            "\n" +
            "Day 10 - \n" +
            "This is the rooster that crowed in the morn that woke\n" +
            "the priest all shaven and shorn that married\n" +
            "the man all tattered and torn that kissed\n" +
            "the maiden all forlorn that milked\n" +
            "that cow with the crumpled horn that tossed\n" +
            "the dog that worried\n" +
            "the cat that killed\n" +
            "the rat that ate\n" +
            "the malt that lay in\n" +
            "the house that Jack built.\n" +
            "\n" +
            "Day 11 - \n" +
            "This is the farmer sowing his corn that kept\n" +
            "the rooster that crowed in the morn that woke\n" +
            "the priest all shaven and shorn that married\n" +
            "the man all tattered and torn that kissed\n" +
            "the maiden all forlorn that milked\n" +
            "that cow with the crumpled horn that tossed\n" +
            "the dog that worried\n" +
            "the cat that killed\n" +
            "the rat that ate\n" +
            "the malt that lay in\n" +
            "the house that Jack built.\n" +
            "\n" +
            "Day 12 - \n" +
            "This is the horse and the hound and the horn that belonged to\n" +
            "the farmer sowing his corn that kept\n" +
            "the rooster that crowed in the morn that woke\n" +
            "the priest all shaven and shorn that married\n" +
            "the man all tattered and torn that kissed\n" +
            "the maiden all forlorn that milked\n" +
            "that cow with the crumpled horn that tossed\n" +
            "the dog that worried\n" +
            "the cat that killed\n" +
            "the rat that ate\n" +
            "the malt that lay in\n" +
            "the house that Jack built.\n\n";

    private Poet poet = null;

    @Before
    public void setUp() throws Exception {
        this.poet = new Poet();
    }

    @Test public void shouldTestForRevealPoetryDayWise() {
        String actualValue = PoetUtils.revealPoetryDayWise(poet.getPoetries(),1);
        String expectedValue = AppConstants.THIS_IS_STRING + AppConstants.DAY1_POETRY + "\n";
        assertEquals(expectedValue,actualValue);

         actualValue = PoetUtils.revealPoetryDayWise(poet.getPoetries(),2);
         expectedValue = AppConstants.THIS_IS_STRING + AppConstants.DAY2_POETRY +"\n" +AppConstants.DAY1_POETRY + "\n";
        assertEquals(expectedValue,actualValue);
    }

    @Test public void shouldTestForRecite() {
        String actualValue = poet.recite();
        String expectedValue = AppConstants.RECITE_ACTUAL_VALUE;
        assertEquals(expectedValue,actualValue);
    }
}
