/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cumulative.poetry;

import org.junit.Test;
import static org.junit.Assert.*;

public class PoetTest {
    @Test public void shouldTestForRevealPoetryDayWise() {
        Poet poet = new Poet();
        String actualValue = poet.revealPoetryDayWise(1);
        String expectedValue = AppConstants.DAY1_POETRY;
        assertEquals(expectedValue,actualValue);
    }

}
