/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cumulative.poetry.service;

import cumulative.poetry.models.ArgsDTO;
import cumulative.poetry.models.Poem;
import cumulative.poetry.models.Poetry;

import java.util.List;


public class Poet implements IPoem{

    private Poem poem;
    private ArgsDTO argsDTO;

    public Poet(Poem poem,ArgsDTO argsDTO) {
        this.poem = poem;
        this.argsDTO = argsDTO;
    }

    public String recite() {
        StringBuilder poetryMessage = new StringBuilder();
        List<Poetry> poetries = poem.getPoetries();
        for(int day = 1; day <= poetries.size(); day++){
                poetryMessage.append("Day "+day+ " - \n");
                poetryMessage.append(poem.revealPoetryDayWise(day,argsDTO.isEchoSelected()));
                poetryMessage.append('\n');
        }
        return poetryMessage.toString();
    }
}
