/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cumulative.poetry.service;

import java.util.List;


public class Poet implements IPoet {

    private Poem poem;

    public Poet(Poem poem) {
        this.poem = poem;
    }

    public String recite() {
        StringBuilder poetryMessage = new StringBuilder();
        List<String> poetries = poem.getPoetries();
        for(int day = 1; day <= poetries.size(); day++){
                poetryMessage.append("Day "+day+ " - \n");
                poetryMessage.append(poem.revealPoetryDayWise(day));
                poetryMessage.append('\n');
        }
        return poetryMessage.toString();
    }
}
